# Generated by Django 6.0.5 on 2026-05-19 04:21

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={'verbose_name': 'Cupón', 'verbose_name_plural': 'Cupones de Descuento'},
        ),
        migrations.AlterModelOptions(
            name='modifier',
            options={'verbose_name': 'Modificador', 'verbose_name_plural': 'Modificadores'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='storesettings',
            options={'verbose_name': 'Configuración Global', 'verbose_name_plural': 'Configuraciones Globales'},
        ),
        migrations.AddField(
            model_name='order',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia / Débito')], default='EFECTIVO', max_length=20),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='descuento_efectivo_porcentaje',
            field=models.IntegerField(default=10, help_text='Porcentaje de descuento por pago en efectivo (ej: 10 para 10%)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='direccion_envio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PREPARANDO', 'Preparando'), ('LISTO', 'Listo para entregar/enviar'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='tipo_entrega',
            field=models.CharField(choices=[('DELIVERY', 'Delivery'), ('TAKE_AWAY', 'Take Away')], default='TAKE_AWAY', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='horario_apertura',
            field=models.TimeField(default=datetime.time(19, 0)),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='horario_cierre',
            field=models.TimeField(default=datetime.time(23, 59)),
        ),
    ]
