# Generated by Django 6.0.5 on 2026-05-19 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_coupon_options_alter_modifier_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='imagen_archivo',
            field=models.ImageField(blank=True, help_text='Sube un archivo desde tu computadora', null=True, upload_to='productos/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='imagen_url',
            field=models.URLField(blank=True, help_text='Link de internet (Ej: Google Imágenes)', null=True),
        ),
    ]
