# Generated by Django 6.0.5 on 2026-05-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_product_imagen_archivo_alter_product_imagen_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='notas_cliente',
            field=models.TextField(blank=True, help_text='Aclaraciones o instrucciones especiales del cliente', null=True),
        ),
    ]
